// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVNMb-rtGFpNmmc_4m9r5M8No5zK2UjA',
    appId: '1:640360004732:web:c270d7361585eea0489df9',
    messagingSenderId: '640360004732',
    projectId: 'flutternote-12080',
    authDomain: 'flutternote-12080.firebaseapp.com',
    storageBucket: 'flutternote-12080.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtBxFlKDrTu5eVqlteuZnE0E1BDiwJlOQ',
    appId: '1:640360004732:android:efe264a15e5c63e9489df9',
    messagingSenderId: '640360004732',
    projectId: 'flutternote-12080',
    storageBucket: 'flutternote-12080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAei-tdSFJmB2EcDlFCLQUWgKhtyL9nzz8',
    appId: '1:640360004732:ios:c67601b877b1a484489df9',
    messagingSenderId: '640360004732',
    projectId: 'flutternote-12080',
    storageBucket: 'flutternote-12080.appspot.com',
    iosClientId: '640360004732-qmbppvpkv18ku82idbl3haqgcdl0vdg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.notappwithfierbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAei-tdSFJmB2EcDlFCLQUWgKhtyL9nzz8',
    appId: '1:640360004732:ios:2c1ff9ccfb11cb19489df9',
    messagingSenderId: '640360004732',
    projectId: 'flutternote-12080',
    storageBucket: 'flutternote-12080.appspot.com',
    iosClientId: '640360004732-mf5dfe28qv3o4d0fjo4oakomhus1uhl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.notappwithfierbase.RunnerTests',
  );
}
